"""INDEPENDENTLY FROZEN pins for all SEVEN shipped Arm 0 bundles.

These are literals. They were transcribed once from the production bundles on 2026-07-30 and are now a
fixed record: a test compares the bundle on disk AGAINST these values, never against values re-read from
the bundle it is checking. Reordering, replacing, adding or deleting one feature in any bundle therefore
fails, because the pin does not move with the bundle.

`n_missing_from_season_dataset` is recorded here as the value MEASURED on 2026-07-30; the test recomputes
it from the real CSV header and the bundle's own feature_cols and asserts equality, so this figure is
checked rather than merely asserted.

Note of fact, not of design: the four VETERAN bundles share one ordered pool (sha 8adff7b4...), and the
WR-rookie and TE-rookie pools are byte-identical to each other (sha 3d9e56f2..., 44 features). RB rookie
is distinct (41 features; 10 features not in the WR/TE pool, which has 13 not in RB's).
"""
BUNDLE_FEATURE_PINS = {
    ("QB", "veteran"): dict(
        bundle="qb_veteran_model.pkl", target="season_total_half_ppr", n=32,
        n_missing_from_season_dataset=0,
        sha256="8adff7b421f514fd6da14d393f8abb21bbcd8f67deca04f9a2691e12bb96b70d",
        feature_cols=(
            "prior_ppg",
            "prior_half_ppr",
            "prior_games",
            "ppg_2yr",
            "ppg_3yr",
            "ppg_trend",
            "career_high_ppg",
            "prior_snap_share_pg",
            "prior_targets_pg",
            "prior_carries_pg",
            "prior_receptions_pg",
            "prior_touches_pg",
            "prior_target_share",
            "prior_air_yards_share",
            "prior_adot",
            "prior_td_rate",
            "prior_yptarget",
            "prior_ypc",
            "prior_rec_epa",
            "prior_rush_epa",
            "age",
            "years_exp",
            "draft_round",
            "draft_pick",
            "prior_team_pass_rate",
            "prior_team_plays",
            "vacated_target_share",
            "vacated_rush_share",
            "coach_changed",
            "qb_changed",
            "prior_games_missed",
            "missed_prior_season",
        )),
    ("RB", "veteran"): dict(
        bundle="rb_veteran_model.pkl", target="season_total_half_ppr", n=32,
        n_missing_from_season_dataset=0,
        sha256="8adff7b421f514fd6da14d393f8abb21bbcd8f67deca04f9a2691e12bb96b70d",
        feature_cols=(
            "prior_ppg",
            "prior_half_ppr",
            "prior_games",
            "ppg_2yr",
            "ppg_3yr",
            "ppg_trend",
            "career_high_ppg",
            "prior_snap_share_pg",
            "prior_targets_pg",
            "prior_carries_pg",
            "prior_receptions_pg",
            "prior_touches_pg",
            "prior_target_share",
            "prior_air_yards_share",
            "prior_adot",
            "prior_td_rate",
            "prior_yptarget",
            "prior_ypc",
            "prior_rec_epa",
            "prior_rush_epa",
            "age",
            "years_exp",
            "draft_round",
            "draft_pick",
            "prior_team_pass_rate",
            "prior_team_plays",
            "vacated_target_share",
            "vacated_rush_share",
            "coach_changed",
            "qb_changed",
            "prior_games_missed",
            "missed_prior_season",
        )),
    ("WR", "veteran"): dict(
        bundle="wr_veteran_model.pkl", target="season_total_half_ppr", n=32,
        n_missing_from_season_dataset=0,
        sha256="8adff7b421f514fd6da14d393f8abb21bbcd8f67deca04f9a2691e12bb96b70d",
        feature_cols=(
            "prior_ppg",
            "prior_half_ppr",
            "prior_games",
            "ppg_2yr",
            "ppg_3yr",
            "ppg_trend",
            "career_high_ppg",
            "prior_snap_share_pg",
            "prior_targets_pg",
            "prior_carries_pg",
            "prior_receptions_pg",
            "prior_touches_pg",
            "prior_target_share",
            "prior_air_yards_share",
            "prior_adot",
            "prior_td_rate",
            "prior_yptarget",
            "prior_ypc",
            "prior_rec_epa",
            "prior_rush_epa",
            "age",
            "years_exp",
            "draft_round",
            "draft_pick",
            "prior_team_pass_rate",
            "prior_team_plays",
            "vacated_target_share",
            "vacated_rush_share",
            "coach_changed",
            "qb_changed",
            "prior_games_missed",
            "missed_prior_season",
        )),
    ("TE", "veteran"): dict(
        bundle="te_veteran_model.pkl", target="season_total_half_ppr", n=32,
        n_missing_from_season_dataset=0,
        sha256="8adff7b421f514fd6da14d393f8abb21bbcd8f67deca04f9a2691e12bb96b70d",
        feature_cols=(
            "prior_ppg",
            "prior_half_ppr",
            "prior_games",
            "ppg_2yr",
            "ppg_3yr",
            "ppg_trend",
            "career_high_ppg",
            "prior_snap_share_pg",
            "prior_targets_pg",
            "prior_carries_pg",
            "prior_receptions_pg",
            "prior_touches_pg",
            "prior_target_share",
            "prior_air_yards_share",
            "prior_adot",
            "prior_td_rate",
            "prior_yptarget",
            "prior_ypc",
            "prior_rec_epa",
            "prior_rush_epa",
            "age",
            "years_exp",
            "draft_round",
            "draft_pick",
            "prior_team_pass_rate",
            "prior_team_plays",
            "vacated_target_share",
            "vacated_rush_share",
            "coach_changed",
            "qb_changed",
            "prior_games_missed",
            "missed_prior_season",
        )),
    ("RB", "rookie"): dict(
        bundle="rb_rookie_model.pkl", target="season_total_half_ppr", n=41,
        n_missing_from_season_dataset=32,
        sha256="619d199d643b658bc1c4375c9e0532c1311f18e1cb6a4d0d449422f4f4c41a28",
        feature_cols=(
            "draft_round",
            "draft_pick",
            "log_pick",
            "age",
            "forty",
            "vertical",
            "broad_jump",
            "cone",
            "shuttle",
            "bench",
            "ht_in",
            "wt",
            "bmi",
            "speed_score",
            "cfb_final_dom",
            "cfb_best_dom",
            "cfb_scrim_ypg",
            "cfb_rush_ypg",
            "cfb_rec_ypg",
            "cfb_ypc",
            "cfb_ypr",
            "cfb_career_scrim_yds",
            "cfb_career_scrim_td",
            "cfb_seasons",
            "cfb_breakout_class",
            "pff_rushing_grades_run",
            "pff_rushing_grades_offense",
            "pff_rushing_elusive_rating",
            "pff_rushing_breakaway_percent",
            "pff_rushing_elu_yco",
            "pff_rushing_avoided_tackles",
            "pff_rushing_first_downs",
            "pff_rushing_touchdowns",
            "pff_receiving_yprr",
            "pff_receiving_routes",
            "prior_team_pass_rate",
            "prior_team_plays",
            "vacated_target_share",
            "vacated_rush_share",
            "coach_changed",
            "qb_changed",
        )),
    ("WR", "rookie"): dict(
        bundle="wr_rookie_model.pkl", target="season_total_half_ppr", n=44,
        n_missing_from_season_dataset=35,
        sha256="3d9e56f25edd3cbe48d5245d238aa433afa8c528b4bffdd22ea4e58a91b17719",
        feature_cols=(
            "draft_round",
            "draft_pick",
            "log_pick",
            "age",
            "forty",
            "vertical",
            "broad_jump",
            "cone",
            "shuttle",
            "bench",
            "ht_in",
            "wt",
            "bmi",
            "speed_score",
            "cfb_final_dom",
            "cfb_best_dom",
            "cfb_scrim_ypg",
            "cfb_rec_ypg",
            "cfb_rec_pg",
            "cfb_ypr",
            "cfb_final_recshare",
            "cfb_career_scrim_yds",
            "cfb_career_scrim_td",
            "cfb_seasons",
            "cfb_breakout_class",
            "pff_receiving_grades_offense",
            "pff_receiving_grades_pass_route",
            "pff_receiving_yprr",
            "pff_receiving_avg_depth_of_target",
            "pff_receiving_contested_catch_rate",
            "pff_receiving_drop_rate",
            "pff_receiving_yards_after_catch_per_reception",
            "pff_receiving_targeted_qb_rating",
            "pff_receiving_routes",
            "pff_receiving_receptions",
            "pff_receiving_yards",
            "pff_receiving_touchdowns",
            "pff_receiving_avoided_tackles",
            "prior_team_pass_rate",
            "prior_team_plays",
            "vacated_target_share",
            "vacated_rush_share",
            "coach_changed",
            "qb_changed",
        )),
    ("TE", "rookie"): dict(
        bundle="te_rookie_model.pkl", target="season_total_half_ppr", n=44,
        n_missing_from_season_dataset=35,
        sha256="3d9e56f25edd3cbe48d5245d238aa433afa8c528b4bffdd22ea4e58a91b17719",
        feature_cols=(
            "draft_round",
            "draft_pick",
            "log_pick",
            "age",
            "forty",
            "vertical",
            "broad_jump",
            "cone",
            "shuttle",
            "bench",
            "ht_in",
            "wt",
            "bmi",
            "speed_score",
            "cfb_final_dom",
            "cfb_best_dom",
            "cfb_scrim_ypg",
            "cfb_rec_ypg",
            "cfb_rec_pg",
            "cfb_ypr",
            "cfb_final_recshare",
            "cfb_career_scrim_yds",
            "cfb_career_scrim_td",
            "cfb_seasons",
            "cfb_breakout_class",
            "pff_receiving_grades_offense",
            "pff_receiving_grades_pass_route",
            "pff_receiving_yprr",
            "pff_receiving_avg_depth_of_target",
            "pff_receiving_contested_catch_rate",
            "pff_receiving_drop_rate",
            "pff_receiving_yards_after_catch_per_reception",
            "pff_receiving_targeted_qb_rating",
            "pff_receiving_routes",
            "pff_receiving_receptions",
            "pff_receiving_yards",
            "pff_receiving_touchdowns",
            "pff_receiving_avoided_tackles",
            "prior_team_pass_rate",
            "prior_team_plays",
            "vacated_target_share",
            "vacated_rush_share",
            "coach_changed",
            "qb_changed",
        )),
}


# =====================================================================================================
# BUNDLE SPECIFICATION PINS — the metadata the experiment ACTUALLY consumes
# =====================================================================================================
# `fit_predict` builds a FRESH estimator every fold via `_make_model(spec["family"], spec["params"])`
# and fits it on that fold's training rows; the serialized `bundle["model"]` object is never used for
# prediction (`arm0_definition` reads only `type(...)` from it, to record a class-name string). So what
# the experiment inherits from a shipped bundle is exactly this specification — feature order, family,
# fixed hyperparameters, preprocessing/null handling and seed — and nothing else.
#
# These are INDEPENDENT literals, transcribed from the bundles on 2026-08-03 and compared against disk.
#
# DISCLOSED, NOT GATED: these hyperparameters were selected under the historical production pipeline,
# which used the pre-repair PFF join. They are frozen pre-experiment and applied IDENTICALLY to ARM_0
# and to every coaching arm, so they cannot differentially favour any arm; the experiment does not
# retune them. See V39_ACTIVATION_MANIFEST.md §0d.
BUNDLE_SPEC_PINS = {
    ("QB", "veteran"): dict(family="lightgbm", seed=42,
        params={"num_leaves": 31, "learning_rate": 0.03, "n_estimators": 400},
        median_impute=None, model_class="lightgbm.sklearn.LGBMRegressor"),
    ("RB", "veteran"): dict(family="lightgbm", seed=42,
        params={"num_leaves": 15, "learning_rate": 0.03, "n_estimators": 400},
        median_impute=None, model_class="lightgbm.sklearn.LGBMRegressor"),
    ("WR", "veteran"): dict(family="lightgbm", seed=42,
        params={"num_leaves": 15, "learning_rate": 0.03, "n_estimators": 400},
        median_impute=None, model_class="lightgbm.sklearn.LGBMRegressor"),
    ("TE", "veteran"): dict(family="lightgbm", seed=42,
        params={"num_leaves": 15, "learning_rate": 0.03, "n_estimators": 400},
        median_impute=None, model_class="lightgbm.sklearn.LGBMRegressor"),
    ("RB", "rookie"): dict(family="lightgbm", seed=42,
        params={"num_leaves": 15, "learning_rate": 0.06, "n_estimators": 400},
        median_impute=None, model_class="lightgbm.sklearn.LGBMRegressor"),
    ("WR", "rookie"): dict(family="lightgbm", seed=42,
        params={"num_leaves": 31, "learning_rate": 0.06, "n_estimators": 400},
        median_impute=None, model_class="lightgbm.sklearn.LGBMRegressor"),
    ("TE", "rookie"): dict(family="lightgbm", seed=42,
        params={"num_leaves": 15, "learning_rate": 0.03, "n_estimators": 400},
        median_impute=None, model_class="lightgbm.sklearn.LGBMRegressor"),
}
