"""ARM 0 REFITS FROM SCRATCH — the serialized estimator never reaches a prediction.

WHY THIS EXISTS. A v3.9o revision refused activation on the grounds that the shipped rookie bundles had
been FIT on the pre-repair PFF join, so their weights were contaminated. That blocker rested on a FALSE
PREMISE and is withdrawn. The experiment inherits a bundle's SPECIFICATION — feature order, family,
fixed hyperparameters, preprocessing/null handling, seed — and builds a brand-new estimator for every
fold. The serialized `bundle["model"]` is never fitted, never predicted from, and never carried into a
fold. These tests pin that property so it cannot quietly stop being true.

The decisive one is `test_POISONING_the_stored_estimator_cannot_change_a_single_prediction`: the stored
object is replaced with a sentinel that raises on ANY use, and the pipeline produces byte-identical
predictions.

No fantasy outcome is read anywhere here. `y` is synthetic, generated by the harness's own
`synthetic_panel`, and the rookie-matrix test reads FEATURES and provenance only.
"""
import ast
import copy
import inspect
import pathlib
import pickle
import sys

import numpy as np
import pandas as pd
import pytest

COACH = pathlib.Path(__file__).resolve().parent.parent
REPO = COACH.parent.parent.parent
sys.path.insert(0, str(COACH))
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import arm0_bundle_pins as PINS                            # noqa: E402
import assemble_real_panel_v39 as ARP                      # noqa: E402
import run_coach_projection_experiment_v39 as EX           # noqa: E402

DATA = COACH / "data"
SMALL_TEAMS = ["ARI", "ATL", "BAL", "BUF", "CAR", "CHI"]
SMALL_SEASONS = list(range(2014, 2020))


def _small_panel():
    return EX.synthetic_panel(seasons=SMALL_SEASONS, teams=SMALL_TEAMS, players_per_team=2,
                              positions=["RB"], seed=11)


def _coach_a():
    return pd.read_csv(DATA / "team_coach_features_design_a_v39.csv")


class ExplodingEstimator:
    """Raises on ANY use. If a prediction ever came from the stored object, this detonates."""

    def __getattr__(self, name):
        raise AssertionError(f"the STORED estimator was used: .{name} accessed")

    def __call__(self, *a, **k):
        raise AssertionError("the STORED estimator was called")

    def __reduce__(self):
        return (ExplodingEstimator, ())


@pytest.fixture(scope="module")
def arm0():
    return EX.arm0_definition()


# =====================================================================================================
# 1. `arm0_definition` returns METADATA, not the estimator
# =====================================================================================================
def test_arm0_definition_does_not_return_the_serialized_model_object(arm0):
    for key, spec in arm0.items():
        assert "model" not in spec, f"{key}: the estimator object is in the spec"
        for name, value in spec.items():
            assert not hasattr(value, "fit"), f"{key}: {name} looks like an estimator"
            assert not hasattr(value, "predict"), f"{key}: {name} looks like an estimator"
        # what IS carried is a class-name STRING
        assert isinstance(spec["model_class"], str)
        assert spec["model_class"] == "lightgbm.sklearn.LGBMRegressor"


def test_arm0_definition_touches_the_stored_model_only_to_read_its_TYPE():
    """AST-level: `bundle["model"]` may appear only inside a `type(...)` call."""
    src = (COACH / "run_coach_projection_experiment_v39.py").read_text(encoding="utf-8")
    fn = next(n for n in ast.walk(ast.parse(src))
              if isinstance(n, ast.FunctionDef) and n.name == "arm0_definition")

    def is_model_sub(node):
        return (isinstance(node, ast.Subscript) and isinstance(node.slice, ast.Constant)
                and node.slice.value == "model")

    inside_type = set()
    for node in ast.walk(fn):
        if isinstance(node, ast.Call) and getattr(node.func, "id", None) == "type":
            for sub in ast.walk(node):
                if is_model_sub(sub):
                    inside_type.add(id(sub))
    uses = [n for n in ast.walk(fn) if is_model_sub(n)]
    assert uses, "the guard would be vacuous if 'model' were never referenced"
    outside = [n for n in uses if id(n) not in inside_type]
    assert not outside, (f"bundle['model'] is used outside type() at line(s) "
                         f"{[n.lineno for n in outside]}")


def test_the_experiment_never_unpickles_a_bundle_into_a_prediction_path():
    src = (COACH / "run_coach_projection_experiment_v39.py").read_text(encoding="utf-8")
    tree = ast.parse(src)
    fn = next(n for n in ast.walk(tree)
              if isinstance(n, ast.FunctionDef) and n.name == "fit_predict")
    body = ast.dump(fn)
    assert '"model"' not in body and "'model'" not in body, "fit_predict references bundle['model']"
    assert "_make_model" in body, "fit_predict does not construct a model"


# =====================================================================================================
# 2. `fit_predict` constructs a FRESH estimator every call
# =====================================================================================================
def test_fit_predict_constructs_a_fresh_estimator_each_call(monkeypatch):
    RB, _ = EX._production_engine()
    made = []
    real_make = RB._make_model

    def spy(family, params):
        m = real_make(family, params)
        made.append(m)          # hold the OBJECT: id() can be recycled once the first is freed,
        return m                # which made an `id` comparison flake in a full-suite run

    monkeypatch.setattr(RB, "_make_model", spy)
    rng = np.random.default_rng(0)
    feats = ["f1", "f2"]
    train = pd.DataFrame({"f1": rng.normal(size=40), "f2": rng.normal(size=40),
                          "y": rng.normal(size=40)})
    test = pd.DataFrame({"f1": rng.normal(size=10), "f2": rng.normal(size=10)})
    spec = {"family": "lightgbm", "params": {"num_leaves": 5, "n_estimators": 10}}

    p1 = EX.fit_predict(spec, train, test, feats)
    p2 = EX.fit_predict(spec, train, test, feats)
    assert len(made) == 2 and made[0] is not made[1], "the same estimator instance was reused"
    np.testing.assert_allclose(p1, p2, err_msg="a fresh fit on identical data must be reproducible")


def test_fit_predict_fits_on_the_frame_it_is_GIVEN(monkeypatch):
    """The fold's own training rows reach `.fit`, so a fold cannot inherit anything."""
    RB, _ = EX._production_engine()
    seen = {}
    real_make = RB._make_model

    def spy(family, params):
        m = real_make(family, params)
        real_fit = m.fit

        def fit(X, y, *a, **k):
            seen["n_rows"] = len(X)
            seen["y"] = np.asarray(y, float).copy()
            return real_fit(X, y, *a, **k)
        m.fit = fit
        return m

    monkeypatch.setattr(RB, "_make_model", spy)
    rng = np.random.default_rng(1)
    train = pd.DataFrame({"f1": rng.normal(size=25), "y": rng.normal(size=25)})
    test = pd.DataFrame({"f1": rng.normal(size=5)})
    EX.fit_predict({"family": "lightgbm", "params": {"num_leaves": 5, "n_estimators": 10}},
                   train, test, ["f1"])
    assert seen["n_rows"] == 25
    np.testing.assert_allclose(seen["y"], train["y"].to_numpy(float))


# =====================================================================================================
# 3. THE DECISIVE ONE — poison the stored estimator; predictions cannot move
# =====================================================================================================
@pytest.fixture(scope="module")
def poisoned_models(tmp_path_factory):
    """A models dir whose bundles carry an EXPLODING estimator. Canon is never touched."""
    out = tmp_path_factory.mktemp("poisoned_models")
    for fname in {v[0] for v in ARP.SHIPPED_ARM0_BUCKETS.values()}:
        b = pickle.loads((ARP.MODELS_DIR / fname).read_bytes())
        b["model"] = ExplodingEstimator()
        (out / fname).write_bytes(pickle.dumps(b))
    return out


def test_the_sentinel_really_does_explode():
    """Guard against a vacuous poisoning: the sentinel must be impossible to use."""
    e = ExplodingEstimator()
    with pytest.raises(AssertionError):
        e.fit
    with pytest.raises(AssertionError):
        e.predict
    with pytest.raises(AssertionError):
        e()
    # but reading its TYPE is safe, which is all `arm0_definition` does
    assert type(e).__name__ == "ExplodingEstimator"


def test_arm0_definition_survives_a_poisoned_estimator(poisoned_models, monkeypatch):
    monkeypatch.setattr(EX, "MODELS", poisoned_models)
    spec = EX.arm0_definition()
    assert len(spec) == 7
    for key, s in spec.items():
        assert s["model_class"].endswith("ExplodingEstimator"), (
            f"{key}: the class-name string did not come from the poisoned object")
        assert "model" not in s


def test_POISONING_the_stored_estimator_cannot_change_a_single_prediction(poisoned_models,
                                                                          monkeypatch):
    """Run the full nested pipeline twice — canonical bundles, then poisoned — and compare.

    If any prediction came from the serialized estimator the poisoned run would raise; if any came
    from stale state the two runs would differ. Synthetic `y` throughout; no outcome is read.
    """
    panel, coach = _small_panel(), _coach_a()
    kwargs = dict(outer_seasons=[2019], positions=["RB"], bootstrap_draws=25, run_placebo=False,
                  verbose=False)

    EX.reset_pipeline_assertions()
    clean = EX.run_experiment(panel, coach, None, **kwargs)

    monkeypatch.setattr(EX, "MODELS", poisoned_models)
    # NON-VACUITY: prove the poisoned bundles are the ones this run reads. Without this, a test that
    # silently kept reading the canonical models would still pass and prove nothing.
    assert all(s["model_class"].endswith("ExplodingEstimator")
               for s in EX.arm0_definition().values()), "the poisoned models dir was not in use"

    EX.reset_pipeline_assertions()
    poisoned = EX.run_experiment(panel, coach, None, **kwargs)

    a = clean["metrics"].sort_values(list(clean["metrics"].columns)).reset_index(drop=True)
    b = poisoned["metrics"].sort_values(list(poisoned["metrics"].columns)).reset_index(drop=True)
    pd.testing.assert_frame_equal(a, b, check_exact=False, rtol=0, atol=0)

    sa = clean["selection"].reset_index(drop=True)
    sb = poisoned["selection"].reset_index(drop=True)
    pd.testing.assert_frame_equal(sa, sb, check_exact=False, rtol=0, atol=0)


# =====================================================================================================
# 4. The rookie folds receive the CORRECTED point-in-time matrix
# =====================================================================================================
@pytest.fixture(scope="module")
def matrix():
    return pd.read_parquet(ARP.ROOKIE_MATRIX)


def test_the_rookie_feature_source_is_the_corrected_matrix():
    """Every rookie bucket declares the corrected, hash-pinned matrix as its input."""
    ARP.verify_rookie_matrix_provenance()
    rows = {(r["position"], r["bucket"]): r for r in ARP.arm0_bucket_table()}
    for key in (("RB", "rookie"), ("WR", "rookie"), ("TE", "rookie")):
        assert rows[key]["source"] == ARP.SOURCE_ROOKIE_MATRIX
        assert rows[key]["n_missing_from_declared_source"] == 0
        assert rows[key]["features_available"] is True


def test_every_rookie_row_the_folds_would_train_on_is_point_in_time(matrix):
    """Read from the artifact the folds consume: no PFF block reaches its own season."""
    for col in ARP.ROOKIE_MATRIX_PROVENANCE:
        nn = matrix[col].notna()
        assert int(nn.sum()) > 0, f"{col} is empty; the check would be vacuous"
        assert int((matrix.loc[nn, "season"] - matrix.loc[nn, col]).min()) >= 1


@pytest.mark.parametrize("position,bucket", [("RB", "rookie"), ("WR", "rookie"), ("TE", "rookie")])
def test_a_rookie_fold_frame_carries_the_corrected_values(matrix, position, bucket):
    """The per-bucket frame a fold would be handed comes from the corrected matrix, in bundle order."""
    frame = ARP.rookie_bucket_frame(matrix, position, bucket)
    fc = tuple(PINS.BUNDLE_FEATURE_PINS[(position, bucket)]["feature_cols"])
    assert tuple(c for c in frame.columns if c in set(fc)) == fc
    pff = [c for c in fc if c.startswith("pff_")]
    assert pff, "the bundle pool has no PFF features; the check would be vacuous"
    ref = matrix.set_index(["player_id", "season"])
    sub = frame.set_index(["player_id", "season"])
    for c in pff:
        pd.testing.assert_series_equal(sub[c], ref.loc[sub.index, c], check_names=False)


def test_fold_training_frames_are_spied_and_carry_no_late_pff(monkeypatch, matrix):
    """End-to-end: intercept every `fit_predict` and assert each training frame is point-in-time."""
    pit = matrix[["player_id", "season"] + list(ARP.ROOKIE_MATRIX_PROVENANCE)]
    checked = {"frames": 0}
    real = EX.fit_predict

    def spy(spec, train, test, features):
        for frame in (train, test):
            if "player_id" not in frame.columns or "season" not in frame.columns:
                continue
            j = frame[["player_id", "season"]].merge(pit, on=["player_id", "season"], how="inner")
            for col in ARP.ROOKIE_MATRIX_PROVENANCE:
                nn = j[col].notna()
                if bool(nn.any()):
                    assert int((j.loc[nn, "season"] - j.loc[nn, col]).min()) >= 1
            checked["frames"] += 1
        return real(spec, train, test, features)

    monkeypatch.setattr(EX, "fit_predict", spy)
    EX.reset_pipeline_assertions()
    EX.run_experiment(_small_panel(), _coach_a(), None, outer_seasons=[2019], positions=["RB"],
                      bootstrap_draws=25, run_placebo=False, verbose=False)
    assert checked["frames"] > 0, "no fold frame was inspected; the spy never ran"


# =====================================================================================================
# 5. The SPECIFICATION is what is pinned, and the hyperparameter limitation is DISCLOSED not gated
# =====================================================================================================
@pytest.mark.parametrize("key", sorted(PINS.BUNDLE_SPEC_PINS))
def test_every_bundle_spec_matches_its_INDEPENDENT_pin(key):
    pin = PINS.BUNDLE_SPEC_PINS[key]
    b = pickle.loads((ARP.MODELS_DIR / ARP.SHIPPED_ARM0_BUCKETS[key][0]).read_bytes())
    assert b["family"] == pin["family"]
    assert dict(b["params"]) == pin["params"]
    assert b["seed"] == pin["seed"]
    assert (None if b["median_impute"] is None else sorted(b["median_impute"])) == pin["median_impute"]
    assert type(b["model"]).__module__ + "." + type(b["model"]).__name__ == pin["model_class"]


def test_the_spec_pins_cover_exactly_the_seven_shipped_buckets():
    assert set(PINS.BUNDLE_SPEC_PINS) == set(ARP.SHIPPED_ARM0_BUCKETS) == set(PINS.BUNDLE_FEATURE_PINS)
    assert len(PINS.BUNDLE_SPEC_PINS) == 7


@pytest.mark.parametrize("field", ["family", "params", "seed", "median_impute"])
def test_mutating_a_pinned_spec_field_is_detected(field):
    """RED: the pin must not move with the bundle."""
    key = ("RB", "rookie")
    pin = dict(PINS.BUNDLE_SPEC_PINS[key])
    mutated = {"family": "xgboost", "params": {"num_leaves": 999}, "seed": 7,
               "median_impute": ["age"]}[field]
    pin[field] = mutated
    b = pickle.loads((ARP.MODELS_DIR / ARP.SHIPPED_ARM0_BUCKETS[key][0]).read_bytes())
    actual = {"family": b["family"], "params": dict(b["params"]), "seed": b["seed"],
              "median_impute": (None if b["median_impute"] is None else sorted(b["median_impute"]))}
    assert actual[field] != pin[field], f"a mutated {field} pin would still pass"


def test_the_spec_contract_is_what_gates_activation_not_the_fitted_weights():
    for r in ARP.arm0_bucket_table():
        assert r["spec_contract_ok"] is True and r["spec_problems"] == []
        assert r["complete"] is True
    assert not hasattr(ARP, "CONTAMINATED_TRAINED_BUCKETS"), (
        "the withdrawn fitted-weights blocker is still present")
    assert not hasattr(ARP, "ROOKIE_BUNDLE_TRAINING_BLOCKER")


@pytest.mark.parametrize("field", sorted(ARP.BUNDLE_SPEC_FIELDS))
def test_an_INCOMPLETE_spec_is_refused(field):
    """RED control: the spec check is not hard-wired to pass."""
    b = pickle.loads((ARP.MODELS_DIR / "rb_rookie_model.pkl").read_bytes())
    broken = {k: v for k, v in b.items() if k != field}
    problems = ARP.bundle_spec_problems(broken)
    assert problems and field in problems[0]


def test_the_frozen_hyperparameter_limitation_is_DISCLOSED_and_NOT_gated():
    d = ARP.FROZEN_HYPERPARAMETER_DISCLOSURE
    assert "frozen pre-experiment" in d and "identically to ARM_0 and every coaching arm" in d
    assert "does not retune" in d
    assert "NOT gated" in d
    # and it genuinely does not gate: readiness is True with the disclosure in force
    assert ARP.activation_readiness()[0] is True


def test_the_disclosure_appears_in_the_activation_manifest():
    """Whitespace-normalised: the document wraps, so a literal substring check is a false negative."""
    raw = (COACH / "V39_ACTIVATION_MANIFEST.md").read_text(encoding="utf-8")
    text = " ".join(raw.replace("*", "").split())
    assert "0d." in raw
    assert "does not retune" in text
    assert "applied identically to ARM_0 and every coaching arm" in text
    assert "not an activation gate" in text
    assert "WITHDRAWN" in raw and "FALSE PREMISE" in raw


# =====================================================================================================
# 6. The two layers, after the withdrawal
# =====================================================================================================
def test_activation_readiness_is_TRUE_on_all_seven_buckets():
    ok, detail = ARP.activation_readiness()
    assert ok is True, detail
    assert "all 7 shipped Arm 0 buckets" in detail


def test_the_gate_refuses_SOLELY_on_run_mode_and_the_locks():
    pf = EX.preflight(pipeline_assertions={k: 3 for k in EX._PIPELINE_ASSERTIONS})
    assert pf["all_ok"] is True and pf["n_checks"] == 21 and pf["n_failed"] == 0
    ok, detail = ARP.authorized_real_gate(pf)
    assert ok is False
    assert "run_mode" in detail and "BOTH LOCKS CLOSED" in detail
    assert "gate 2" not in detail, f"gate 2 must be clear; it said: {detail}"
    assert EX.REAL_FIT_AUTHORIZED is False
    assert EX.real_fit_lock_state() == (False, False)


def test_nothing_was_retrained_in_this_pass():
    import hashlib
    for (pos, bucket), pin in PINS.BUNDLE_FEATURE_PINS.items():
        fname = ARP.SHIPPED_ARM0_BUCKETS[(pos, bucket)][0]
        fc = tuple(pickle.loads((ARP.MODELS_DIR / fname).read_bytes())["feature_cols"])
        assert fc == tuple(pin["feature_cols"])
        assert hashlib.sha256("\n".join(fc).encode("utf-8")).hexdigest() == pin["sha256"]
    pf = EX.preflight(require_pipeline_assertions=False)
    assert pf["checks"]["production_models_identical"]["ok"] is True
    assert pf["checks"]["protected_hashes"]["ok"] is True
